### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by JosephEoff** [xiaolaba/Curve_Tracer_testing#1]
Hi.  It is rather cool that you like my software enough  to repost it with some useful batch files.

It is not so cool that you changed the license.

"Rodriguez" is licensed under  the [GNU General Public License, version 2.](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)

Your repository has the license set to MIT.  By the terms of the GPL, only the copyright holder (me, Joseph Eoff) can change the license.

Please change the license on the repository to GPL V2, or delete the repository.

**Comment by JosephEoff** [comment]
Additionally, there is a binary build of Rodriguez in my repository ([Release 1.0.0](https://github.com/JosephEoff/Rodriguez/releases/tag/v1.0.0)) so there's no real need to provide a binary of your own.

**Comment by xiaolaba** [comment]
thanks. i had delete the license and add another, please teach me whether the license is sutible one for the choice.

**Comment by JosephEoff** [comment]
Thank you for fixing the license.

GPL V2.0 is the correct license.

The GPL V20 license requires that you keep the same license when using code licensed under it.  The GPL V2 license also requires that you make the code itself available to other users.  You have a link to my project in the ReadMe.  I'll accept that as "providing the source code."

You don't need to refer to this in your ReadMe.  Just keep the license as is, and make sure to always refer to my project so that others can find the most current version.

**Comment by JosephEoff** [comment]
I saw that you had some trouble with negative values for the diode and collector current.

Both are caused by the same thing.

The real cause is that I swapped A2 and A3 when I drew the schematics.  That made the calculated values for the collector current come out negative.  The diode function uses the same analog inputs as the collector measurements, so that messed up the diode measurements as well.

Since you are the second person to have this problem, I changed the Arduino code to use the analog inputs as shown in the schematic diagrams.

All you need to do is to download the new Rodriguez.ino file and burn it to your Arduino.

**Comment by xiaolaba** [comment]
thanks Joseph,we will try out later on when come back to town.

**Comment by JosephEoff** [comment]
Your transistor traces show only a single line because you didn't follow the directions in the [wiki](https://github.com/JosephEoff/Rodriguez/wiki/4.-Breadboard-setup---NPN) or the comments in my [blog pages.](https://josepheoff.github.io/posts/iv7)

In addition to the base resistor in the diagrams, you must include a larger series resistor.  The base resistor in the diagram is used to measure the base current.  To use Rodriguez with any half way decent transistor you will have to put a 200k or higher resistor in series with the base of your transistor.  The current gain of any modern transistor is so high that the collector current will quickly go outside of Rodriguez's limit of 5mA collector current.

You must also enter the correct value for the base resistor you used in the circuit into the provided field in the GUI.  I used 3.3k, you used 10k.  You must put that value into the R_base field.  You must also enter the correct value for R_collector and V_ref.

The program code (Python and Arduino) both use only a carriage return to end the lines when communicating over the serial port.  There is no " bug deep inside the python3.x"

The serial routine in Rodriguez.ino grew out of a simpler routine that took only a single numeric value (as text) and a carriage return.  At a later stage, I implemented the "C" and "B" commands and removed the case for the carriage return.

I usually make the serial routines of my Arduino .ino files so that they can be commanded through any terminal program (PuTTY, or the Arduino serial terminal, or any other terminal program.)  Those might send a carriage return or a carriage return and a line feed.  My serial routines usually ignore the line feed but watch for the carriage return.

**Comment by xiaolaba** [comment]
hi , thanks for giving hints of the Rb and greater resistance would be, we are waiting for purchase and the pouch delivery, so far we have ten of few resistors only about 220/1k/10k, too lazy to series those up as no enough counts.

CRLF redundant is about what we have seen with Win10 used, a simple test suite both Arduino code and the python code had been used to verify the seeing again, no doubt, I did not know why. In case you would like to see and help to figure out the possible clues or able to replicates the same, I could send you the code and upload to repo, basically a cut out version of your original code with some adding sauce. \r or \n or \r\n really given difference, this is not the first time to reveal such odd thing in between unix/win.

**Comment by JosephEoff** [comment]
You will have to show me what you mean about "redundant" CRLF.

The Rodriguez Arduino part uses the [Arduino Serial.println](https://www.arduino.cc/reference/en/language/functions/communication/serial/println/) function, which always sends a CRLF at the end of each line.

It reads individual characters, ignoring line ends and reacting only to the command codes (B or C.)

The Python program uses serial.readline, which reads the lines sent to it from the Arduino.  This works correctly under Linux.  It should also work correctly under Windows. 
The Python program sends only CR.

Where are you seeing redundant CRLF?

**Comment by JosephEoff** [comment]
You keep writing "we." Are you working on this in a group?

**Comment by xiaolaba** [comment]
hi, there are friends to play together, sort of a group. thanks for your hints of the serial protocol, I will test more about CRLF this weekend by free time, perhaps the logger used or issue.
